build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.4

      cache:
        disabled: false
        directories:
          - ~/.composer/cache

      project_setup:
        override: true

      tests:
        override:
          - php-scrutinizer-run

before_commands:
  - "composer update --no-dev --prefer-stable --prefer-source --classmap-authoritative"
