name: 'Run Tests'

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.can-fail }}
    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4]
        symfony: [4.4.*, 5.1.*, 5.2.*]
        composer-flags: ['--prefer-stable']
        phpunit-flags: ['--coverage-clover clover.xml']
        can-fail: [false]
        include:
          - php: 7.2
            symfony: 4.4.*
            composer-flags: '--prefer-stable --prefer-lowest'
            phpunit-flags: '--coverage-clover clover.xml'
            can-fail: false
          - php: 7.4
            symfony: 5.3.*@dev
            composer-flags: '--prefer-stable'
            phpunit-flags: '--coverage-clover clover.xml'
            can-fail: true
          - php: 8.0
            symfony: 5.1.*
            composer-flags: '--ignore-platform-req=php'
            phpunit-flags: ''
            can-fail: true

    name: PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }} - Composer ${{ matrix.composer-flags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-symfony-${{ matrix.symfony }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}-flags-${{ matrix.composer-flags }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: curl, iconv, mbstring, pdo, pdo_sqlite, sqlite, zip
          coverage: pcov

      - name: Install dependencies
        run: |
          composer global require --no-scripts --no-plugins symfony/flex
          SYMFONY_REQUIRE=${{ matrix.symfony }} composer update ${{ matrix.composer-flags }} --prefer-dist --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit ${{ matrix.phpunit-flags }}

      - name: Upload coverage
        if: matrix.php != '8.0'
        run: |
          wget https://github.com/scrutinizer-ci/ocular/releases/download/1.6.0/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover clover.xml
