name: 'Run Tests'

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.can-fail }}
    strategy:
      fail-fast: true
      matrix:
        php: ['8.1']
        symfony: ['5.4.*', '6.0.*', '6.1.*', '6.2.*']
        composer-flags: ['--prefer-stable']
        can-fail: [false]
        include:
          - php: '8.1'
            symfony: '5.4.*'
            composer-flags: '--prefer-stable --prefer-lowest'
            can-fail: false

    name: "PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}${{ matrix.composer-flags != '' && format(' - Composer {0}', matrix.composer-flags) || '' }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-symfony-${{ matrix.symfony }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}-flags-${{ matrix.composer-flags }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, flex
          extensions: curl, iconv, mbstring, pdo, pdo_sqlite, sqlite, zip
          coverage: none

      - name: Install dependencies
        run: |
          composer update ${{ matrix.composer-flags }} --prefer-dist --no-suggest
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}

      - name: Execute tests
        run: vendor/bin/phpunit
