name: 'Run Tests'

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.next-symfony }}
    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4]
        symfony: [3.4.*, 4.4.*, 5.0.*]
        composer-flags: ['--prefer-stable']
        next-symfony: [false]
        include:
          - php: 7.2
            symfony: 3.4.*
            composer-flags: '--prefer-stable --prefer-lowest'
            next-symfony: false
          - php: 7.4
            symfony: 5.1.*@rc
            composer-flags: '--prefer-stable'
            next-symfony: true
          - php: 7.4
            symfony: 5.2.*@dev
            composer-flags: '--prefer-stable'
            next-symfony: true

    name: PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }} - Composer ${{ matrix.composer-flags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-symfony-${{ matrix.symfony }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}-flags-${{ matrix.composer-flags }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, iconv, mbstring, pdo, pdo_sqlite, sqlite, zip
          coverage: none

      - name: Install dependencies
        run: |
          composer global require --no-scripts --no-plugins symfony/flex
          composer update ${{ matrix.composer-flags }} --prefer-dist --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit
